# DogeRat Web Admin - Docker Compose Configuration

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: dogerat-db
    environment:
      POSTGRES_DB: ${DB_NAME:-dogerat}
      POSTGRES_USER: ${DB_USER:-dogerat}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-dogerat}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - dogerat-network

  # Backend Server
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: dogerat-server
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://${DB_USER:-dogerat}:${DB_PASSWORD:-changeme}@postgres:5432/${DB_NAME:-dogerat}
      DB_TYPE: postgres
      JWT_SECRET: ${JWT_SECRET:-change-this-in-production}
      JWT_EXPIRY: ${JWT_EXPIRY:-24h}
      CORS_ORIGIN: ${CORS_ORIGIN}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@dogerat.local}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-Admin@123456}
    volumes:
      - uploads:/app/uploads
      - logs:/app/logs
    ports:
      - "${SERVER_PORT:-5000}:5000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - dogerat-network

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: dogerat-client
    ports:
      - "${CLIENT_PORT:-80}:80"
    depends_on:
      - server
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - dogerat-network

  # Ngrok tunnel for backend API (expose server:5000 to internet)
  ngrok:
    image: ngrok/ngrok:latest
    container_name: dogerat-ngrok
    depends_on:
      - server
    environment:
      NGROK_AUTHTOKEN: 349egkHrIWSE7NzXDFCEnw9ulph_5PtSyXrWpJDq4tJHWhzFu
    command: http --url=evelina-duchesslike-solely.ngrok-free.dev server:5000
    ports:
      - "4040:4040"  # Ngrok web interface
    restart: unless-stopped
    networks:
      - dogerat-network

volumes:
  postgres_data:
    driver: local
  uploads:
    driver: local
  logs:
    driver: local

networks:
  dogerat-network:
    driver: bridge
